name: Build and Deploy

on:
  workflow_dispatch: {}

env:
  BUCKET_NAME : "coffee-supply-chain-2"
  AWS_REGION : "ap-northeast-1"
  GITHUB_REF: "master"

jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
          role-session-name: GitHub-Action-Role
          aws-region: ${{ env.AWS_REGION }}

      - name: Extract branch name
        shell: bash
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >>$GITHUB_OUTPUT
        id: extract_branch

      - name: Extract commit hash
        shell: bash
        run: echo "git_hash=$(git rev-parse --short "$GITHUB_SHA")" >>$GITHUB_OUTPUT
        id: extract_hash          
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm i
      - run: npm run dev

      # Copy build directory to S3
      - name:  Copy build to S3
        run: |
          zip -r project.zip . -x node_modules\* dist\* .git\*
          aws s3 cp project.zip s3://coffee-supply-chain-2/code-deploy-3/project.zip
        
  deploy:
    name: Deploy to EC2
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
    - uses: actions/checkout@v3
    - run: |
        echo "Deploying branch"

    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
        aws-region: ${{ env.AWS_REGION }}
    - run: |
        aws deploy create-deployment --application-name node-app --deployment-group-name ec2-app --s3-location bucket=coffee-supply0-2,key=code-deploy-3/project.zip,bundleType=zip